{% set name = "intake-erddap" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-erddap-{{ version }}.tar.gz
  sha256: 91b4164c9a6b38d62f65cf2400a00c8cc70e07109c0173dea4731dc052ec72ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.8
    - appdirs
    - erddapy
    - fsspec
    - intake
    - intake-xarray
    - numpy
    - pandas
    - requests
    - xarray
    - cf_pandas

test:
  imports:
    - intake_erddap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/intake-erddap
  summary: ERDDAP plugin for Intake
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lukecampbell
    - kthyng
