{% set name = "intake-erddap" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-erddap-{{ version }}.tar.gz
  sha256: 2641c7d42fda216e582575d89f2ad34108469482d719876ff08a6060785a9783

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - setuptools_scm_git_archive
    - pip
  run:
    - python >=3.8
    - appdirs
    - erddapy
    - fsspec
    - intake
    - intake-xarray
    - numpy
    - pandas
    - requests
    - xarray
    - cf_pandas

test:
  imports:
    - intake_erddap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/intake-erddap
  summary: ERDDAP plugin for Intake
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lukecampbell
    - kthyng
