{% set name = "intake-erddap" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd602cf55bb5e67630a359ee27cfd967a844b184dda6292f7ecbf5f8558f52d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools_scm_git_archive
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - erddapy
    - fsspec
    - intake
    - intake-xarray
    - numpy
    - pandas
    - requests
    - xarray
    - cf_pandas

test:
  imports:
    - intake_erddap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/axiom-data-science/intake-erddap
  summary: ERDDAP plugin for Intake
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lukecampbell
    - kthyng
